
server:
  port: 8001

spring:
  application:
    name: message
  zipkin:
    base-url: http://zipkin-server
  sleuth:
    sampler:
      percentage: 1.0
management:
  health:
    refresh:
      enabled: true
  security:
    enabled: false
