
server:
  port: 8001
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: message
management:
  health:
    refresh:
      enabled: true
  security:
    enabled: false
kun:
  user:
    id: 1
    name: shi